import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Plus, Search, X } from 'lucide-react'
import { api, label, query } from '../services'
import type { Profile, Row } from '../types'
import { Badge, Button, Card, Field, Input, Select, Table } from '../components/ui'

type Kind = 'products' | 'warehouses' | 'locations' | 'adjustments' | 'moves' | 'settings'
const config = {
  products: { title: 'Products', subtitle: 'Keep your product catalog accurate and easy to find.', fields: [['name','Product name','text'],['sku','SKU','text'],['category_id','Category','category'],['unit','Unit','text'],['unit_cost','Unit cost','number'],['sales_price','Sales price','number'],['reorder_level','Reorder level','number'],['description','Description','text']] },
  warehouses: { title: 'Warehouses', subtitle: 'Manage where your inventory lives.', fields: [['name','Warehouse name','text'],['short_code','Short code','text'],['address','Address','text']] },
  locations: { title: 'Locations', subtitle: 'Organize shelves, receiving, and dispatch areas.', fields: [['name','Location name','text'],['short_code','Short code','text'],['warehouse_id','Warehouse','warehouse']] },
  adjustments: { title: 'Inventory adjustments', subtitle: 'Reconcile a physical count with system stock.', fields: [['product_id','Product','product'],['warehouse_id','Warehouse','warehouse'],['location_id','Location','location'],['counted_quantity','Counted quantity','number'],['reason','Reason','reason'],['notes','Notes','text']] },
} as const

export default function ResourcePage({ kind, profile }: { kind: Kind; profile: Profile }) {
  const [params] = useSearchParams()
  const [rows, setRows] = useState<Row[]>([]), [products, setProducts] = useState<Row[]>([]), [warehouses, setWarehouses] = useState<Row[]>([]), [locations, setLocations] = useState<Row[]>([]), [categories, setCategories] = useState<Row[]>([]), [inventory, setInventory] = useState<Row[]>([])
  const [search, setSearch] = useState(params.get('search') || ''), [filter, setFilter] = useState(''), [page, setPage] = useState(1), [editing, setEditing] = useState<Row | null | 'new'>(null)
  const [form, setForm] = useState<Record<string, string>>({}), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState<Row | null>(null)
  const resource = kind === 'moves' ? 'stock_movements' : kind
  async function load() { try { const [r,p,w,l,c,i] = await Promise.all([api<Row[]>(`/${resource}${query({limit:100})}`),api<Row[]>('/products?limit=100'),api<Row[]>('/warehouses?limit=100'),api<Row[]>('/locations?limit=100'),api<Row[]>('/categories?limit=100'),api<Row[]>('/inventory?limit=100')]); setRows(r); setProducts(p); setWarehouses(w); setLocations(l); setCategories(c); setInventory(i); setError('') } catch(e) { setError((e as Error).message) } }
  useEffect(() => { if (kind !== 'settings') load() }, [kind])
  const filtered = useMemo(() => rows.filter(r => { const text=JSON.stringify(r).toLowerCase(); return text.includes(search.toLowerCase()) && (!filter || r.status === filter || r.warehouse_id === filter || r.category_id === filter || r.movement_type === filter) }), [rows,search,filter])
  const visible = filtered.slice((page-1)*10,page*10)
  function start(row: Row | 'new') { setEditing(row); setForm(row === 'new' ? {} : Object.fromEntries(Object.entries(row).map(([k,v]) => [k, v == null ? '' : String(v)]))); setError(''); setNotice('') }
  async function save(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError('')
    try {
      const fields = config[kind as keyof typeof config].fields
      const data: Record<string, unknown> = {}
      for (const [key,,type] of fields) data[key] = type === 'number' ? Number(form[key] || 0) : (form[key] || '')
      if (kind === 'adjustments') {
        const loc = locations.find(l => l.id === data.location_id)
        if (loc?.warehouse_id !== data.warehouse_id) throw new Error('Choose a location in the selected warehouse.')
      }
      if (editing === 'new') await api(`/${resource}`, {method:'POST',body:JSON.stringify(data)})
      else if (editing) await api(`/${resource}/${editing.id}`, {method:'PUT',body:JSON.stringify(data)})
      setNotice(editing === 'new' ? 'Record created.' : 'Record updated.'); setEditing(null); await load()
    } catch(e) { setError((e as Error).message) } finally { setBusy(false) }
  }
  async function remove(row: Row) { if (!window.confirm(`Remove ${row.name || row.reference}? This cannot be undone.`)) return; try { await api(`/${resource}/${row.id}`, {method:'DELETE'}); setNotice(kind==='products' ? 'Product archived.' : 'Record removed.'); await load() } catch(e) { setError((e as Error).message) } }
  async function apply(row: Row) { if (!window.confirm('Confirm this physical count and update inventory?')) return; try { await api(`/adjustments/${row.id}/validate`,{method:'POST'}); setNotice('Adjustment applied. Stock and movement history updated.'); await load() } catch(e) { setError((e as Error).message) } }
  if (kind === 'settings') return <div className="page"><div className="page-head"><div><span className="eyebrow">WORKSPACE</span><h1>Settings</h1><p>Your account and access level.</p></div></div><Card className="settings-card"><div className="avatar large">{profile.full_name.charAt(0).toUpperCase()}</div><div><h2>{profile.full_name}</h2><p>{profile.email}</p><Badge status="done">{profile.role}</Badge></div></Card><p className="muted">Managers can manage catalog records and approve inventory adjustments. Ask your database administrator to change a role.</p></div>
  const meta = kind === 'moves' ? {title:'Move history',subtitle:'A complete trail of every stock change.'} : config[kind]
  const columns: Record<string,string[]> = { products:['Product','SKU','Category','Unit cost','Reorder','Status','Actions'], warehouses:['Warehouse','Code','Address','Locations','Actions'], locations:['Location','Code','Warehouse','Actions'], adjustments:['Reference','Product','Location','System','Counted','Difference','Status','Actions'], moves:['Reference','Date','Product','From','To','Quantity','Type','Responsible'] }
  const cells = (r: Row): React.ReactNode[] => {
    const actions = <div className="row-actions" onClick={e=>e.stopPropagation()}>{kind !== 'adjustments' && <Button variant="ghost" onClick={() => start(r)}>Edit</Button>}{kind === 'adjustments' && r.status === 'draft' && <Button variant="secondary" onClick={() => apply(r)}>Apply count</Button>}{kind !== 'adjustments' && <Button variant="ghost" onClick={() => remove(r)}>{kind === 'products' ? 'Archive' : 'Delete'}</Button>}</div>
    switch(kind) {
      case 'products': return [<strong>{String(r.name)}</strong>,String(r.sku),label(r.category_id,categories),`₹${Number(r.unit_cost).toLocaleString()}`,String(r.reorder_level),<Badge status={r.is_active ? 'done' : 'canceled'}>{r.is_active ? 'Active':'Archived'}</Badge>,profile.role === 'manager' ? actions : '—']
      case 'warehouses': return [<strong>{String(r.name)}</strong>,String(r.short_code),String(r.address || '—'),locations.filter(l => l.warehouse_id === r.id).length,profile.role === 'manager' ? actions : '—']
      case 'locations': return [<strong>{String(r.name)}</strong>,String(r.short_code),label(r.warehouse_id,warehouses),profile.role === 'manager' ? actions : '—']
      case 'adjustments': return [String(r.reference),label(r.product_id,products),label(r.location_id,locations),r.system_quantity == null ? '—' : String(r.system_quantity),String(r.counted_quantity),r.difference == null ? '—' : String(r.difference),<Badge status={String(r.status)}>{String(r.status)}</Badge>,profile.role === 'manager' ? actions : '—']
      case 'moves': return [<strong>{String(r.reference)}</strong>,new Date(String(r.created_at)).toLocaleString(),label(r.product_id,products),label(r.source_location_id,locations),label(r.destination_location_id,locations),String(r.quantity),<Badge status={String(r.movement_type)}>{String(r.movement_type)}</Badge>,String(r.responsible_user || '—').slice(0,8)]
    }
  }
  return <div className="page"><div className="page-head"><div><span className="eyebrow">{kind === 'moves' ? 'INSIGHTS / ACTIVITY' : 'MANAGE / '+kind.toUpperCase()}</span><h1>{meta.title}</h1><p>{meta.subtitle}</p></div>{kind !== 'moves' && profile.role === 'manager' && <Button onClick={() => start('new')}><Plus size={18}/> {kind === 'adjustments' ? 'New adjustment' : `Add ${kind.slice(0,-1)}`}</Button>}</div>{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}<Card className="data-card"><div className="toolbar"><div className="search-control"><Search size={17}/><Input placeholder={`Search ${kind}…`} value={search} onChange={e => {setSearch(e.target.value);setPage(1)}}/></div>{kind === 'moves' && <Select value={filter} onChange={e => {setFilter(e.target.value);setPage(1)}}><option value="">All movement types</option>{['receipt','delivery','transfer','adjustment'].map(x => <option key={x}>{x}</option>)}</Select>}{kind === 'adjustments' && <Select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All statuses</option><option>draft</option><option>done</option></Select>}{kind === 'products' && <Select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{String(c.name)}</option>)}</Select>}{kind === 'locations' && <Select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All warehouses</option>{warehouses.map(w => <option key={w.id} value={w.id}>{String(w.name)}</option>)}</Select>}</div><Table columns={columns[kind]} rows={visible.map(cells)} onRow={kind==='moves'||kind==='warehouses' ? i=>setSelected(visible[i]) : undefined}/><div className="pagination"><span>Showing {visible.length} of {filtered.length}</span><div><button disabled={page===1} onClick={() => setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={page*10>=filtered.length} onClick={() => setPage(page+1)}>Next</button></div></div></Card>
    {editing && kind !== 'moves' && <div className="modal-backdrop" onMouseDown={e => {if(e.target===e.currentTarget)setEditing(null)}}><div className="modal"><div className="modal-head"><div><span className="eyebrow">{editing==='new'?'CREATE':'EDIT'} RECORD</span><h2>{editing==='new' ? `New ${meta.title.toLowerCase()}` : `Edit ${meta.title.toLowerCase()}`}</h2></div><button onClick={() => setEditing(null)} aria-label="Close"><X size={20}/></button></div><form onSubmit={save}><div className="form-grid">{config[kind].fields.map(([key,title,type]) => <Field key={key} label={title}>{['warehouse','location','product','category','reason'].includes(type) ? <Select required={type !== 'category'} value={form[key] || ''} onChange={e => setForm({...form,[key]:e.target.value})}><option value="">Select {title.toLowerCase()}</option>{(type==='warehouse' ? warehouses : type==='location' ? locations.filter(l=>!form.warehouse_id || l.warehouse_id===form.warehouse_id) : type==='product' ? products : type==='category' ? categories : ['Physical Count','Damaged','Lost','Correction','Other'].map(x=>({id:x,name:x}))).map(option=><option value={option.id} key={option.id}>{String(option.name)}</option>)}</Select> : <Input required={['name','sku','short_code'].includes(key)} type={type} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} value={form[key] || ''} onChange={e => setForm({...form,[key]:e.target.value})}/>}</Field>)}</div>{error && <div className="alert error">{error}</div>}<div className="modal-actions"><Button variant="secondary" type="button" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save record'}</Button></div></form></div></div>}
    {selected && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="modal"><div className="modal-head"><h2>{kind==='warehouses' ? String(selected.name) : `Movement ${String(selected.reference)}`}</h2><button onClick={()=>setSelected(null)} aria-label="Close"><X size={20}/></button></div>{kind==='warehouses' ? <><p className="muted">{String(selected.address||'No address')} · {String(selected.short_code)}</p><h3>Locations</h3><div className="detail-list">{locations.filter(l=>l.warehouse_id===selected.id).map(l=><div key={l.id}><span>{String(l.name)} · {String(l.short_code)}</span><strong>{inventory.filter(i=>i.location_id===l.id).reduce((sum,i)=>sum+Number(i.quantity_on_hand),0)} units</strong></div>)}</div></> : <div className="detail-list">{Object.entries(selected).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><strong>{String(value ?? '—')}</strong></div>)}</div>}</div></div>}
  </div>
}
