import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Boxes, Search } from 'lucide-react'
import { api, label, watchTables } from '../services'
import type { Product, Row } from '../types'
import { Badge, Card, Input, Select, Table } from '../components/ui'

export default function StockPage() {
  const [products, setProducts] = useState<Product[]>([]), [inventory, setInventory] = useState<Row[]>([]), [warehouses, setWarehouses] = useState<Row[]>([]), [categories, setCategories] = useState<Row[]>([])
  const [search, setSearch] = useState(''), [warehouse, setWarehouse] = useState(''), [category, setCategory] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1), [error, setError] = useState('')
  useEffect(() => { let alive = true; const load = async () => { try { const [p,i,w,c] = await Promise.all([api<Product[]>('/products?limit=100'), api<Row[]>('/inventory?limit=100'), api<Row[]>('/warehouses?limit=100'), api<Row[]>('/categories?limit=100')]); if (alive) { setProducts(p); setInventory(i); setWarehouses(w); setCategories(c) } } catch(e) { if (alive) setError((e as Error).message) } }; load(); const stop=watchTables(['products','inventory'],load); const timer=setInterval(load,8000); return () => { alive=false; clearInterval(timer); stop() } }, [])
  const rows = useMemo(() => products.filter(p => p.is_active).map(p => { const lots = inventory.filter(i => i.product_id === p.id && (!warehouse || i.warehouse_id === warehouse)); const onHand = lots.reduce((n,i) => n+Number(i.quantity_on_hand),0), reserved = lots.reduce((n,i) => n+Number(i.quantity_reserved),0); const state = onHand <= 0 ? 'Out of Stock' : onHand <= Number(p.reorder_level) ? 'Low Stock' : 'In Stock'; return { ...p, onHand, reserved, free: onHand-reserved, state } }).filter(p => (!warehouse || inventory.some(i => i.product_id === p.id && i.warehouse_id === warehouse)) && (!category || p.category_id === category) && (!status || p.state === status) && (`${p.name} ${p.sku}`).toLowerCase().includes(search.toLowerCase())), [products,inventory,warehouse,category,status,search])
  const visible = rows.slice((page-1)*10,page*10)
  return <div className="page"><div className="page-head"><div><span className="eyebrow">CATALOG / STOCK</span><h1>Stock overview</h1><p>See what is on hand, reserved, and ready to use.</p></div><Link to="/products" className="btn btn-primary">+ Add product</Link></div>{error && <div className="alert error">{error}</div>}<div className="summary-strip"><Boxes size={18}/><strong>{rows.length}</strong> products in view <span>·</span> <strong>{rows.reduce((n,r) => n+r.onHand,0).toLocaleString()}</strong> total units on hand</div><Card className="data-card"><div className="toolbar"><div className="search-control"><Search size={17}/><Input placeholder="Search product or SKU" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }}/></div><Select value={category} onChange={e => { setCategory(e.target.value); setPage(1) }}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{String(c.name)}</option>)}</Select><Select value={warehouse} onChange={e => { setWarehouse(e.target.value); setPage(1) }}><option value="">All warehouses</option>{warehouses.map(w => <option key={w.id} value={w.id}>{String(w.name)}</option>)}</Select><Select value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}><option value="">All statuses</option>{['In Stock','Low Stock','Out of Stock'].map(s => <option key={s}>{s}</option>)}</Select></div><Table columns={['Product','Unit cost','On hand','Free to use','Reserved','Reorder level','Status']} rows={visible.map(p => [<div className="product-cell"><span className="product-initial">{p.name.charAt(0)}</span><div><strong>{p.name}</strong><small>{p.sku} · {label(p.category_id,categories)}</small></div></div>,`₹${Number(p.unit_cost).toLocaleString()}`,p.onHand,p.free,p.reserved,p.reorder_level,<Badge status={p.state === 'In Stock' ? 'done' : p.state === 'Low Stock' ? 'waiting' : 'canceled'}>{p.state}</Badge>])}/><div className="pagination"><span>Showing {visible.length} of {rows.length} products</span><div><button disabled={page===1} onClick={() => setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={page*10>=rows.length} onClick={() => setPage(page+1)}>Next</button></div></div></Card></div>
}
